### ISSUE TITLE
[BUG][Register Page] The loading pop-up displays forever after registering new user

### ISSUE THREAD

**Issue by thxlong** [hoangvu96z/Hvtekshop_App#14]
**Description:** The loading pop-up displays forever after registering new user.
**Step:**

1. Input require fill in Register Page.
2. Click Submit button.

**Expected result:** Navigate to Login page without loading pop-up.
**Actual result:** Navigate to Login page with loading pop-up displays forever.

Note: Please remove line code: `this.loading = false` before reproduce this issue.
![image](https://user-images.githubusercontent.com/15044300/176503302-658fe0f2-d669-493b-a299-d700f25c8458.png)

**Comment by thxlong** [comment]
I think it is synchronous problem @hoangvu96z 
`this.loading = false` is not set again after run to subscriber

**Comment by hoangvu96z** [comment]
Root cause : loading variable set = false (line 114) right after set = true before calling api. This variable should set = false when call api transaction completed.
Pls refer the PR : https://github.com/hoangvu96z/Hvtekshop_App/pull/15
